name: Linting and Formatting

on: [push]

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - name: Check Python version
        run: |
          python3 -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools wheel autopep8
          pip list
      - name: Lint python files
        run: |
          echo "Running autopep8..."
          find . -name '*.py' -exec autopep8 --in-place '{}' \;
          echo "Linting and formatting is complete"
